server:
    port: 8081
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: theanh2906
        url: jdbc:h2:file:./data/main_db
        username: theanh2906
    flyway:
        enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                validator:
                    apply_to_ddl: false
        show-sql: true
