server:
  port: 8081
spring:
  datasource:
    hikari:
      schema: public
    password: BenNa1402*
    url: jdbc:postgresql://theanh2906.ddns.net:5432/tools
    username: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740845971597-quolkmkd830njlgsl1cmpgk4q8pm5u5l.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:4200
            scope:
              - email
              - profile
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
